---

name: Packer

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'packer/**'
      - '.github/workflows/packerbuild.yml'


jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # initialise
      - name: initialise
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: .
          working_directory: packer/

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: az-wireguard-image.pkr.hcl
          working_directory: packer/

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: az-wireguard-image.pkr.hcl
          working_directory: packer
        env:
          PACKER_LOG: 1
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}